server:
  port: 8080

spring:
  main:
    banner-mode: off
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/hermes
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'false'
    hibernate:
      ddl-auto: update


logging:
  level:
    org.springframework: INFO

hermes:
  app:
    jwtExpirationMs: '86400000'
    jwtSecret: hermesSecret